### ISSUE TITLE
Issue with Canari install-package sploitego Kali 

### ISSUE THREAD

**Issue by JCFL-Dev** [allfro/sploitego#10]
Hey,
Having an issues installing the sploitego package with Canari on Kali. The following error is returned after I run the Canari command. Any help would be great. Thanks

`root@kali:~# canari install-package sploitego
Traceback (most recent call last):
  File "/usr/local/bin/canari", line 4, in <module>
    __import__('pkg_resources').run_script('canari==1.1', 'canari')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 745, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1670, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/canari-1.1-py2.7.egg/EGG-INFO/scripts/canari", line 20, in <module>
    canari_main()
  File "/usr/local/lib/python2.7/dist-packages/canari-1.1-py2.7.egg/canari/commands/framework.py", line 33, in _func
    return func(self.parser.parse_args(args_, namespace))
  File "/usr/local/lib/python2.7/dist-packages/canari-1.1-py2.7.egg/canari/commands/common.py", line 67, in canari_main
    opts.command_function(opts)
  File "/usr/local/lib/python2.7/dist-packages/canari-1.1-py2.7.egg/canari/commands/install_package.py", line 57, in install_package
    opts = parse_args(args)
  File "/usr/local/lib/python2.7/dist-packages/canari-1.1-py2.7.egg/canari/commands/install_package.py", line 23, in parse_args
    uproot()
  File "/usr/local/lib/python2.7/dist-packages/canari-1.1-py2.7.egg/canari/commands/common.py", line 91, in uproot
    login = os.getlogin()
OSError: [Errno 2] No such file or directory
`

**Comment by JCFL-Dev** [comment]
@allfro Is this user error on my part? I installed canari and sploitego from tar as in Ubuntu video as easy_install doesn't run due to missing packages on pypi

**Comment by JCFL-Dev** [comment]
@allfro I have found a hack to bypass this.  `os.popen("whoami").read()`  I then hit an error on `user = pwd.getpwnam(login) keyerror: 'getpwnam(): name not found: root\n'.` I bypassed this by hard coding in like so 
`user = pwd.getpwnam("root").` Looks like Sploitego installed. Great tool. I'll get back if I run into any issues. Thanks

**Comment by allfro** [comment]
The pypi issue has been resolved. PyPi now insists that they want to host all the python packages. Previously they were located on my website.

**Comment by JCFL-Dev** [comment]
@allfro Thanks. Great tool

**Comment by HachimanSec** [comment]
Hi @PhilDunphy 
did you find any other issue? I am experiencing the same problem but hardocding "root" doesnt work.

@allfro , is there any current development to fix this or is this somewhat dead? Would be really sad as it seems to be a very cool project

**Comment by captainhowdy1** [comment]
It is odd to me, I have had this issue continuously through half a dozen installations of Debian and Umbunto. 
I have never actually not encountered this problem and have only a ever gotten Canari to work in two instances. Outside of that I always recieve errors indicating the commands to perform any command are incorrect or that I cannot run canari because Ineed "module name 2.0 but you have module name3.1, which is not compatible" or I just run flat into an error 1. 
Any attempt to google this issue has always lead to me a post from around 2016 that ends with claiming the issue has now been resolved in an update. I have only been able to use Maltego fractionally as efficiently and have yet to ever see a functioning Canari, Sploitego, or  Malformity module. If this is user error I would love finding out how I can correct whatever is occurring. Currently I cannot downgrade my pip packages without an error 1 and while canari shows fully installed folders and commands in the /bin/ folder, the python path seems correct from my laymans experience.  

pip2.7 install canari
Requirement already satisfied: canari in /usr/local/lib/python2.7/dist-packages (3.2.2)
Requirement already satisfied: six in /usr/local/lib/python2.7/dist-packages (from canari) (1.10.0)
Requirement already satisfied: pyopenssl in /usr/local/lib/python2.7/dist-packages (from canari) (16.2.0)
Requirement already satisfied: Twisted in /usr/lib/python2.7/dist-packages (from canari) (17.9.0)
Requirement already satisfied: future in /usr/lib/python2.7/dist-packages (from canari) (0.15.2)
Requirement already satisfied: flask in /usr/local/lib/python2.7/dist-packages (from canari) (0.11.1)
Requirement already satisfied: pyasn1 in /usr/local/lib/python2.7/dist-packages (from canari) (0.1.9)
Requirement already satisfied: service-identity in /usr/lib/python2.7/dist-packages (from canari) (16.0.0)
Requirement already satisfied: mr.bob in /usr/local/lib/python2.7/dist-packages (from canari) (0.1.2)
Requirement already satisfied: lxml in /usr/local/lib/python2.7/dist-packages (from canari) (3.6.0)
Requirement already satisfied: safedexml in /usr/local/lib/python2.7/dist-packages (from canari) (0.5.1)
Requirement already satisfied: argparse in /usr/lib/python2.7 (from canari) (1.2.1)
Requirement already satisfied: cryptography>=1.3.4 in /usr/local/lib/python2.7/dist-packages (from pyopenssl->canari) (1.5.3)
Requirement already satisfied: Jinja2>=2.4 in /usr/lib/python2.7/dist-packages (from flask->canari) (2.10)
Requirement already satisfied: Werkzeug>=0.7 in /usr/lib/python2.7/dist-packages (from flask->canari) (0.14.1)
Requirement already satisfied: click>=2.0 in /usr/lib/python2.7/dist-packages (from flask->canari) (6.7)
Requirement already satisfied: itsdangerous>=0.21 in /usr/lib/python2.7/dist-packages (from flask->canari) (0.24)
Requirement already satisfied: setuptools in /usr/local/lib/python2.7/dist-packages (from mr.bob->canari) (39.2.0)
Requirement already satisfied: defusedxml in /usr/local/lib/python2.7/dist-packages (from safedexml->canari) (0.5.0)
Requirement already satisfied: cffi>=1.4.1 in /usr/local/lib/python2.7/dist-packages (from cryptography>=1.3.4->pyopenssl->canari) (1.11.5)
Requirement already satisfied: enum34 in /usr/lib/python2.7/dist-packages (from cryptography>=1.3.4->pyopenssl->canari) (1.1.6)
Requirement already satisfied: ipaddress in /usr/lib/python2.7/dist-packages (from cryptography>=1.3.4->pyopenssl->canari) (1.0.17)
Requirement already satisfied: idna>=2.0 in /usr/local/lib/python2.7/dist-packages (from cryptography>=1.3.4->pyopenssl->canari) (2.6)
Requirement already satisfied: pycparser in /usr/local/lib/python2.7/dist-packages (from cffi>=1.4.1->cryptography>=1.3.4->pyopenssl->canari) (2.18)
ishell 0.1.4 requires readline, which is not installed.
mitmproxy 0.18.2 has requirement requests<2.12,>=2.9.1, but you'll have requests 2.18.4 which is incompatible.
sploitego 1.5 has requirement scapy==2.1.0, but you'll have scapy 2.4.0 which is incompatible.
