### ISSUE TITLE
cannot import name cookie

### ISSUE THREAD

**Issue by Widdershinns** [allfro/sploitego#12]
/opt# canari create-profile sploitego
Looking for transforms in sploitego...
Traceback (most recent call last):
  File "/usr/local/bin/canari", line 4, in <module>
    __import__('pkg_resources').run_script('canari==3.0', 'canari')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 742, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1497, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/canari-3.0-py2.7.egg/EGG-INFO/scripts/canari", line 22, in <module>
    canari_main()
  File "/usr/local/lib/python2.7/dist-packages/canari-3.0-py2.7.egg/canari/commands/framework.py", line 33, in _func
    return func(self.parser.parse_args(args_, namespace))
  File "/usr/local/lib/python2.7/dist-packages/canari-3.0-py2.7.egg/canari/commands/common.py", line 60, in canari_main
    opts.command_function(opts)
  File "/usr/local/lib/python2.7/dist-packages/canari-3.0-py2.7.egg/canari/commands/create_profile.py", line 57, in create_profile
    transform_package = TransformDistribution(opts.package)
  File "/usr/local/lib/python2.7/dist-packages/canari-3.0-py2.7.egg/canari/pkgutils/transform.py", line 68, in __init__
    (self.name, self.name, e))
**_ImportError: Does not appear to be a valid canari package. Couldn't import the 'sploitego.transforms' package in 'sploitego'. Error message: cannot import name cookie_**

Any insight would be great!

**Comment by Widdershinns** [comment]
forgot to change alias to Python 2.6*

**Comment by Widdershinns** [comment]
Doesn't look related to Python versioning.  Please see;

http://stackoverflow.com/questions/9252543/importerror-cannot-import-name-x
http://stackoverflow.com/questions/17845366/importerror-cannot-import-name

**Comment by Widdershinns** [comment]
Doesn't look related to Python versioning. (also does the same whether I'm in a virtualenv or not)

Please see;

http://stackoverflow.com/questions/9252543/importerror-cannot-import-name-x
http://stackoverflow.com/questions/17845366/importerror-cannot-import-name

user@machine:# canari create-profile sploitego
Looking for transforms in sploitego...
Traceback (most recent call last):
File "/usr/local/bin/canari", line 4, in 
import('pkg_resources').run_script('canari==3.0', 'canari')
File "/usr/lib/python2.7/dist-packages/pkg_resources/init.py", line 742, in run_script
self.require(requires)[0].run_script(script_name, ns)
File "/usr/lib/python2.7/dist-packages/pkg_resources/init.py", line 1497, in run_script
exec(code, namespace, namespace)
File "/usr/local/lib/python2.7/dist-packages/canari-3.0-py2.7.egg/EGG-INFO/scripts/canari", line 22, in 
canari_main()
File "/usr/local/lib/python2.7/dist-packages/canari-3.0-py2.7.egg/canari/commands/framework.py", line 33, in func
return func(self.parser.parse_args(args, namespace))
File "/usr/local/lib/python2.7/dist-packages/canari-3.0-py2.7.egg/canari/commands/common.py", line 60, in canari_main
opts.command_function(opts)
File "/usr/local/lib/python2.7/dist-packages/canari-3.0-py2.7.egg/canari/commands/create_profile.py", line 57, in create_profile
transform_package = TransformDistribution(opts.package)
File "/usr/local/lib/python2.7/dist-packages/canari-3.0-py2.7.egg/canari/pkgutils/transform.py", line 68, in init
(self.name, self.name, e))
ImportError: Does not appear to be a valid canari package. Couldn't import the 'sploitego.transforms' package in 'sploitego'. Error message: cannot import name cookie
user@machine:#
