### ISSUE TITLE
Error Message: cannot import name cookie

### ISSUE THREAD

**Issue by Widdershinns** [allfro/sploitego#14]
Clarification of Issue*
OS = Kali rolling 2016.2

_"with all pre-req's installed*"_

pip install canari
pip install sploitego
canari create-profile sploitego

_receives the following error;_

Looking for transforms in sploitego...
Traceback (most recent call last):
  File "/usr/local/bin/canari", line 22, in <module>
    canari_main()
  File "/usr/local/lib/python2.7/dist-packages/canari/commands/framework.py", line 33, in _func
    return func(self.parser.parse_args(args_, namespace))
  File "/usr/local/lib/python2.7/dist-packages/canari/commands/common.py", line 60, in canari_main
    opts.command_function(opts)
  File "/usr/local/lib/python2.7/dist-packages/canari/commands/create_profile.py", line 57, in create_profile
    transform_package = TransformDistribution(opts.package)
  File "/usr/local/lib/python2.7/dist-packages/canari/pkgutils/transform.py", line 68, in __init__
    (self.name, self.name, e))
_**ImportError: Does not appear to be a valid canari package. Couldn't import the 'sploitego.transforms' package in 'sploitego'. Error message: cannot import name cookie**_

**Comment by n-collery** [comment]
Identical problem on Mac OS 10.12.5, python 2.7.13, latest canari 3.1.3 and sploitego install, both from pip and from git (clone).

$ canari create-profile sploitego
Looking for transforms in sploitego...
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/bin/canari", line 4, in <module>
    __import__('pkg_resources').run_script('canari==3.1.3', 'canari')
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1500, in run_script
    exec(code, namespace, namespace)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/canari-3.1.3-py2.7.egg/EGG-INFO/scripts/canari", line 22, in <module>
    canari_main()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/canari-3.1.3-py2.7.egg/canari/commands/framework.py", line 33, in _func
    return func(self.parser.parse_args(args_, namespace))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/canari-3.1.3-py2.7.egg/canari/commands/common.py", line 61, in canari_main
    opts.command_function(opts)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/canari-3.1.3-py2.7.egg/canari/commands/create_profile.py", line 57, in create_profile
    transform_package = TransformDistribution(opts.package)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/canari-3.1.3-py2.7.egg/canari/pkgutils/transform.py", line 69, in __init__
    (self.name, self.name, e))
**ImportError: Does not appear to be a valid canari package. Couldn't import the 'sploitego.transforms' package in 'sploitego'. Error message: cannot import name cookie**

**Comment by captainhowdy1** [comment]
Was any workaround or solution found to this issue? I am still having the same issue.

**Comment by allfro** [comment]
Sploitego is not compatible with Canari 3. Please download the code and
change the dependency in setup.py to canari==1.1 and do python setup.py
install again. I would suggest uninstalling canari first with pip uninstall
canari

**Comment by captainhowdy1** [comment]
Thank you for your response and help. It is greatly appreciated.
