### ISSUE TITLE
"ValueError: No JSON object could be decoded" when running a transform

### ISSUE THREAD

**Issue by cantonic** [allfro/sploitego#8]
I get the following error with some transforms:

```
<MaltegoMessage><MaltegoTransformExceptionMessage><Exceptions><Exception>Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/canari/maltego/utils.py", line 222, in local_transform_runner
    ) if get_transform_version(transform_module.dotransform) == 2 else transform_module.dotransform(
  File "/usr/local/lib/python2.7/site-packages/sploitego-1.5-py2.7.egg/sploitego/transforms/pipltolocation.py", line 35, in dotransform
    last_name=request.entity.lastname or ''
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
</Exception></Exceptions></MaltegoTransformExceptionMessage></MaltegoMessage>
```

**Comment by allfro** [comment]
Not sure how to reproduce that error. Could you tell me how you managed to get those exceptions ?
